
spring.application.name=bank-app
spring.data.mongodb.uri=mongodb://mongo:mongo@localhost:27017/bank-app?authSource=admin&retryWrites=false

spring.security.user.name=user
spring.security.user.password=password

bank.api.security.matchers=/api/v1/customers/**,/api/v1/accounts/**,/api/v1/transactions/**